FROM php:8.2-apache

# 1. Install Database Drivers
RUN docker-php-ext-install pdo pdo_mysql

# 2. ENABLE MOD_REWRITE (Crucial for your .htaccess to work)
RUN a2enmod rewrite

# 3. Change Apache's root folder to point to 'public'
ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# 4. Copy files
COPY . /var/www/html/